#ifndef AW_FM_INDEX_GLOBALS_H
#define AW_FM_INDEX_GLOBALS_H

#define CACHE_LINE_SIZE_IN_BYTES        64
#define POSITIONS_PER_FM_BLOCK_BYTE     7
#define BYTES_PER_AVX2_REGISTER         32
#define POSITIONS_PER_FM_BLOCK          BYTES_PER_AVX2_REGISTER * POSITIONS_PER_FM_BLOCK_BYTE
#define AMINO_CARDINALITY               20

#define MAXIMUM_FILE_PATH_LENGTH        8192

#endif /* end of include guard: AW_FM_INDEX_GLOBALS_H */
