# this test is deprecated
# TEST_SRC	= occSpeedTest.c
# SRC 			= $(wildcard ../../src/*.c)
# CFLAGS 	= -std=c11 -Wall -mtune=native -g -fopenmp -ldivsufsort64 -mavx2 -I../../libdivsufsort/build/include
# EXE 		= occSpeedTest.out
# bwtTest: $(SRC)
# 	gcc $(TEST_SRC) $(SRC) -o $(EXE) $(CFLAGS)
