# this test is deprecated
# TEST_SRC = popcountTest.c
# SRC = $(wildcard ../../src/*.c)

# CFLAGS = -std=c11 -fsanitize=address -Wall -mtune=native -fopenmp -mavx2 -O0 -g
# LDLIBS = ../../lib/FastaVector/build/libfastavector_static.a ../../lib/libdivsufsort/build/lib/libdivsufsort64.a

# EXE = popcountTest.out

# backtraceTest: $(SRC)
# 	gcc $(TEST_SRC) $(SRC) -o $(EXE) $(CFLAGS) $(LDLIBS)

# .PHONY: clean
# clean:
# 	rm -f $(EXE)