name: Build and Test

on: [push, pull_request]

jobs:
  check-build:
    runs-on: ubuntu-20.04
    container:
      image: traviswheelerlab/awfmindex-build
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - uses: actions/checkout@v1
      - run: cmake . && make
  
  check-legacy-build:
    runs-on: ubuntu-20.04
    container:
      image: traviswheelerlab/awfmindex-build
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - uses: actions/checkout@v1
      - run: make -f Makefile_legacy && make -f Makefile_legacy static

  check-format:
    runs-on: ubuntu-20.04
    container:
      image: traviswheelerlab/awfmindex-build
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - uses: actions/checkout@v1
      - run: ./tool/check-format.sh
